name: Build install test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
        include:
          - os: ubuntu-22.04
            apt: 10
          - os: macos-14
            brew: 20
          - os: windows-latest
            winget: 30
    steps:
      - name: mamba-setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            pkg-config
            clang
            hdf5
            pybind11[global]
            graphviz
            pytables
            numpy
            matplotlib
            vpython
            lxml
            doxygen
            setuptools
            wheel
            meson
            ninja
            meson-python
            gsl
          post-cleanup: all
          generate-run-shell: false            
      - name: Display Python version
        run: |          
          python -c "import sys; print(sys.version)"
      - if: ${{ matrix.apt }}
        run: |
          sudo apt-get -y install libgsl0-dev libgsl-dev libhdf5-dev
      - if: ${{ matrix.brew }}
        run: |
          brew uninstall pkg-config || :
            brew uninstall pkg-config@0.29.2
          brew install gsl
          brew install hdf5
      - name: checkout
        uses: actions/checkout@v4          
      - name: Build and install (non-windows)
        if: runner.os != 'Windows' 
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate moose
          python -c "import sys; print('#' * 60, sys.version)"
          pip install python-libsbml
          pip install .
          python -c "import moose; moose.le()"
      - name: Build and install (windows)
        if: runner.os == 'Windows' 
        run: |
          micromamba shell hook -s powershell | Out-String | Invoke-Expression
          micromamba activate moose
          python -c "import sys; print('#' * 60, sys.version)"
          pip install python-libsbml
          pip install .
          python -c "import moose; moose.le()"
