name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            apt: 10
          - os: macos-14
            brew: 20
    steps:
      - name: mamba-setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            pip
            pkg-config
            clang
            meson
            ninja
            meson-python
            hdf5
            pybind11[global]
            graphviz
            pytables
            numpy
            matplotlib
            vpython
            lxml
            doxygen
            setuptools
            wheel
      - name: Display Python version
        run: |          
          python -c "import sys; print(sys.version)"
      - if: ${{ matrix.apt }}
        run: sudo apt-get install libhdf5-dev libgsl0-dev graphviz-dev python3-lxml doxygen meson ninja
      - if: ${{ matrix.brew }}
        run: |
          brew install gsl
          brew install hdf5
          brew install graphviz
          brew install cmake
          brew install doxygen
      - name: install python module dependencies via pip
        run: |
          pip install pybind11[global]
          pip install python-libsbml
      - name: checkout
        uses: actions/checkout@v4          
      - name: build and install
        run: |
          pip install .
          python -c "import moose; moose.le()"
